sudo: required

services:
  - docker

before_install:
  - docker build -t brunocandia/Docker-Flow-Client -f dockerfile.dev .

script:
  - docker run brunocandia/Docker-Flow-Client npm run test -- --coverage